# Generated by Django 5.0.3 on 2024-04-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
